name: cicd

# main ブランチへのPull Request と Merge をトリガーに指定
on:
  push:
    branches:
      - main
      - stg
  pull_request:
    branches:
      - main
      - stg

env:
  # GCPのPROJECT_ID
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  # Region
  REGION: ${{ secrets.GCP_REGION }}
  # Artifact RegistryのRepository名（事前に作成しておく）
  BASE_REPOSITORY_NAME: ${{ secrets.BASE_REPOSITORY_NAME }}

  SERVICE_ACCOUNT: ${{ secrets.TERRAFORM_SERVICE_ACCOUNT }}
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

# ジョブ / ステップ / アクションの定義
jobs:
  is-allow-pull-request:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Print ${{ github.event.pull_request.base.ref }}, ${{ github.event.pull_request.head.ref }}"
      - name: Check base branch
        if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref != 'stg'
        run: |
          echo "Pull requests to main are only allowed from the stg branch."
          exit 1
  # src配下のファイルの変更検知
  setup:
    runs-on: ubuntu-latest
    needs: is-allow-pull-request
    if: success()
    outputs:
      src: ${{ steps.filter.outputs.src }}
      env_string: ${{ steps.set-environment.outputs.ENV_STRING }}
      repository_name: ${{ steps.set-environment.outputs.REPOSITORY_NAME }}
    steps:
      - uses: actions/checkout@v4

      - name: Make the script files executable
        working-directory: .github/scripts/
        run: chmod +x set_env.sh

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - 'src/**'
      - name: Set environment string
        id: set-environment
        run: ./.github/scripts/set_env.sh
        env:
          BASE_REPOSITORY_NAME: ${{ secrets.BASE_REPOSITORY_NAME }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_OUTPUT: $GITHUB_OUTPUT
  build:
    needs: [is-allow-pull-request, setup]
    if: needs.setup.outputs.src == 'true' || github.ref == 'refs/heads/stg'
    runs-on: ubuntu-latest
    outputs:
      env_string: ${{ needs.setup.outputs.env_string }}
      repository_name: ${{ needs.setup.outputs.repository_name }}
    defaults:
      run:
        working-directory: .
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    # Workload Identity 連携
    steps:
      # https://cloud.google.com/iam/docs/using-workload-identity-federation#generate-automatic
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: ./.github/workflows/authenticate.yaml
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - id: 'setup-to-google-cloud'
        name: 'Setup Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: 'Authorize Docker push'
        # Artifact Registryにpushできるように認証をおこなう
        # Container Registryのときには不要だったArtifact RegistryではRegionの指定が必須
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/Dockerfile.prd
          push: true
          tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ needs.setup.outputs.repository_name }}/${{ needs.setup.outputs.env_string }}-api-image:${{ github.sha }}
  terraform:
    needs: [is-allow-pull-request, setup, build]
    runs-on: ubuntu-latest
    if: ${{ !failure() }} && needs.validate.result == 'success'
    environment: ${{ needs.setup.outputs.env_string || needs.build.outputs.env_string }}
    defaults:
      run:
        working-directory: ./terraform/resource_stack
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    # Workload Identity 連携
    steps:
      - uses: actions/checkout@v4

      - name: Make the script files executable
        working-directory: .github/scripts/
        run: chmod +x get_latest_tag.sh terraform_plan_comment.sh

      - name: Authenticate to Google Cloud
        uses: ./.github/workflows/authenticate.yaml
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - id: 'Setup to Google Cloud'
        name: 'Setup Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: Get Latest Tag
        id: get-latest-tag
        working-directory: .github/scripts/
        run: get_latest_tag.sh
        env:
          REGION: ${{ env.REGION }}
          PROJECT_ID: ${{ env.PROJECT_ID }}
          REPOSITORY_NAME: ${{ needs.setup.outputs.repository_name || needs.build.outputs.repository_name }}
          ENV_STRING: ${{ needs.setup.outputs.env_string || needs.build.outputs.env_string }}
          GITHUB_OUTPUT: $GITHUB_OUTPUT

      # https://github.com/hashicorp/setup-terraform
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Workspace Select
        run: terraform workspace select ${{ needs.setup.outputs.env_string || needs.build.outputs.env_string }} || terraform workspace new ${{ needs.setup.outputs.env_string || needs.build.outputs.env_string }}

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -var=docker_tag=${{ steps.get-latest-tag.outputs.tag }}
        continue-on-error: true

      - name: print
        run: echo ${{ steps.get-latest-tag.outputs.tag }}

      - name: Set Terraform Plan Comment
        id: terraform_plan_comment
        working-directory: .github/scripts/
        run: set_terraform_plan_comment.sh
        env:
          FMT_OUTCOME: ${{ steps.fmt.outcome }}
          INIT_OUTCOME: ${{ steps.init.outcome }}
          VALIDATE_OUTCOME: ${{ steps.validate.outcome }}
          VALIDATE_OUTPUT: ${{ steps.validate.outputs.stdout }}
          PLAN_OUTCOME: ${{ steps.plan.outcome }}
          PLAN_OUTPUT: ${{ steps.plan.outputs.stdout }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_WORKING_DIR: ${{ env.tf_actions_working_dir }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          GITHUB_OUTPUT: $GITHUB_OUTPUT

      - name: Comment Terraform Plan
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const params = {
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ steps.terraform_plan_comment.outputs.message }}'
            }
            await github.rest.issues.createComment(params)

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      # mainとstgにpushした場合は appｌｙ が実行される
      - name: Terraform Apply
        if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/stg') && github.event_name == 'push'
        run: terraform apply -auto-approve -var=docker_tag=${{ steps.get-latest-tag.outputs.tag }}

      # main ブランチに push した場合にだけ stg環境のdestroyが実行される
      - name: Terraform Destroy Stg
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          terraform workspace select stg || terraform workspace new stg
          terraform destroy -auto-approve -var=docker_tag=''