name: cicd

# main ãƒ–ãƒ©ãƒ³ãƒã¸ã®Pull Request ã¨ Merge ã‚’ãƒˆãƒªã‚¬ãƒ¼ã«æŒ‡å®š
on:
  push:
    branches:
      - main
      - stg
  pull_request:
    branches:
      - main
      - stg

env:
  # GCPã®PROJECT_ID
  PROJECT_ID: youtube-data-api-385206
  # Region
  REGION: asia-northeast1
  # Artifact Registryã®Repositoryåï¼ˆäº‹å‰ã«ä½œæˆã—ã¦ãŠãï¼‰
  BASE_REPOSITORY_NAME: youtube-data-api-repository

# ã‚¸ãƒ§ãƒ– / ã‚¹ãƒ†ãƒƒãƒ— / ã‚¢ã‚¯ã‚·ãƒ§ãƒ³ã®å®šç¾©
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Print ${{ github.event.pull_request.base.ref }}, ${{ github.event.pull_request.head.ref }}"
      - name: Check base branch
        if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref != 'stg'
        run: |
          echo "Pull requests to main are only allowed from the stg branch."
          exit 1
  # srcé…ä¸‹ã®ãƒ•ã‚¡ã‚¤ãƒ«ã®å¤‰æ›´æ¤œçŸ¥
  setup:
    runs-on: ubuntu-latest
    needs: validate
    if: success()
    outputs:
      src: ${{ steps.filter.outputs.src }}
      env_string: ${{ steps.set-environment.outputs.ENV_STRING }}
      repository_name: ${{ steps.set-environment.outputs.REPOSITORY_NAME }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - 'src/**'
      - name: Set environment string
        id: set-environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ github.base_ref }}" == "main" ]]; then
            echo "ENV_STRING=prd" >> "$GITHUB_OUTPUT"
            echo "REPOSITORY_NAME=prd-$BASE_REPOSITORY_NAME" >> "$GITHUB_OUTPUT"
            echo "Set ENV_STRING=prd, REPOSITORY_NAME=prd-$BASE_REPOSITORY_NAME"
          elif [[ "${{ github.ref }}" == "refs/heads/stg" || "${{ github.base_ref }}" == "stg" ]]; then
            echo "ENV_STRING=stg" >> "$GITHUB_OUTPUT"
            echo "REPOSITORY_NAME=stg-$BASE_REPOSITORY_NAME" >> "$GITHUB_OUTPUT"
            echo "Set ENV_STRING=stg, REPOSITORY_NAME=stg-$BASE_REPOSITORY_NAME"
          fi
  build:
    needs: [validate, setup]
    if: needs.setup.outputs.src == 'true' || github.ref == 'refs/heads/stg'
    runs-on: ubuntu-latest
    outputs:
      env_string: ${{ needs.setup.outputs.env_string }}
      repository_name: ${{ needs.setup.outputs.repository_name }}
    defaults:
      run:
        working-directory: .
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    # Workload Identity é€£æº
    steps:
      # https://cloud.google.com/iam/docs/using-workload-identity-federation#generate-automatic
      - uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/1051886801059/locations/global/workloadIdentityPools/youtube-data-api-pool/providers/youtube-data-api-provider'
          service_account: 'terraform@youtube-data-api-385206.iam.gserviceaccount.com'

      - id: 'setup'
        name: 'Setup Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: 'Authorize Docker push'
        # Artifact Registryã«pushã§ãã‚‹ã‚ˆã†ã«èªè¨¼ã‚’ãŠã“ãªã†
        # Container Registryã®ã¨ãã«ã¯ä¸è¦ã ã£ãŸArtifact Registryã§ã¯Regionã®æŒ‡å®šãŒå¿…é ˆ
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/Dockerfile.prd
          push: true
          tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ needs.setup.outputs.repository_name }}/${{ needs.setup.outputs.env_string }}-api-image:${{ github.sha }}
  test:
    needs: [validate, setup, build]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.validate.result }}
      - run: echo ${{ needs.build.result }}
      - run: echo ${{ needs.setup.outputs.src }}

  terraform:
    needs: [validate, setup, build]
    runs-on: ubuntu-latest
    if: needs.validate.result == 'success' && (needs.build.result == 'success' || needs.setup.outputs.src != 'true')
    environment: ${{ needs.setup.outputs.env_string || needs.build.outputs.env_string }}
    defaults:
      run:
        working-directory: ./terraform/resource_stack
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    # Workload Identity é€£æº
    steps:
      - run: echo ${{needs.setup.outputs.src}}
      - uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/1051886801059/locations/global/workloadIdentityPools/youtube-data-api-pool/providers/youtube-data-api-provider'
          service_account: 'terraform@youtube-data-api-385206.iam.gserviceaccount.com'

      - id: 'setup'
        name: 'Setup Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: Get Latest Tag
        id: get-latest-tag
        run: |
          LATEST_TAG=$(gcloud artifacts docker images list --sort-by=~CREATE_TIME --include-tags --format='value(TAGS)' --filter="tags:*" --limit=1 ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ needs.setup.outputs.repository_name || needs.build.outputs.repository_name }}/${{ needs.setup.outputs.env_string || needs.build.outputs.env_string }}-api-image)
          echo "Latest image tag is $LATEST_TAG"
          echo "tag=$LATEST_TAG" >> "$GITHUB_OUTPUT"

      # https://github.com/hashicorp/setup-terraform 
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Workspace Select
        run: terraform workspace select ${{ needs.setup.outputs.env_string || needs.build.outputs.env_string }} || terraform workspace new ${{ needs.setup.outputs.env_string || needs.build.outputs.env_string }}

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -var=docker_tag=${{ steps.get-latest-tag.outputs.tag }}
        continue-on-error: true

      - name: print
        run: echo ${{ steps.get-latest-tag.outputs.tag }}

      - name: Comment Terraform Plan
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style ğŸ–Œ\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization âš™ï¸\`${{ steps.init.outcome }}\`
            #### Terraform Validation ğŸ¤–\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>
            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`
            </details>
            #### Terraform Plan ğŸ“–\`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            </details>
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      # mainã¨stgã«pushã—ãŸå ´åˆã¯ appï½Œï½™ ãŒå®Ÿè¡Œã•ã‚Œã‚‹
      - name: Terraform Apply
        if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/stg') && github.event_name == 'push'
        run: terraform apply -auto-approve -var=docker_tag=${{ steps.get-latest-tag.outputs.tag }}

      # main ãƒ–ãƒ©ãƒ³ãƒã« push ã—ãŸå ´åˆã«ã ã‘ stgç’°å¢ƒã®destroyãŒå®Ÿè¡Œã•ã‚Œã‚‹
      - name: Terraform Destroy Stg
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          terraform workspace select stg || terraform workspace new stg
          terraform destroy -auto-approve -var=docker_tag=''